"""Hoymiles G3 input-register catalog (transcribed verbatim from reference manifest.py::R)."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Register:
    addr: int
    key: str
    label: str
    dtype: str
    scale: float = 1.0
    unit: str | None = None
    domain: str = ""
    doc: str = ""
    source: tuple[str, ...] = ()
    kind: str = "input"          # "input" (FC04) or "holding" (FC03)
    enum: dict | None = None     # {raw int: display label} for status registers
    bitmap: dict | None = None   # {bit index: display label} for fault bitmaps


# Composite ("derived") registers are not read from any physical Modbus address:
# their value is computed from the `source` component registers. Give them fake
# addresses well above the 16-bit Modbus space (0–65535) so it's obvious they're
# synthetic and they can never collide with a real register.
SYNTHETIC_BASE = 100_000


REGISTERS: tuple[Register, ...] = (
    # --- Status / safety -------------------------------------------------
    Register(0, "workstatus", "Work Status", "U16", 1, None, domain="inverter",
             enum={0: "Power-up", 1: "Standby", 2: "Grid test", 3: "Grid on",
                   4: "Fault", 5: "Islanded", 6: "Bypass"}),
    Register(1, "powerdsp_fm_ver", "Power DSP Firmware Version", "U16", 1, None, domain="inverter"),
    Register(19, "sw_fault", "Software Fault", "H32", 1, None, domain="inverter"),
    Register(21, "hw_fault", "Hardware Fault", "H32", 1, None, domain="inverter"),

    # --- PV strings ------------------------------------------------------
    Register(SYNTHETIC_BASE + 0, "pv_total_power", "PV Total Power", "U16", 1, "W", domain="pv",
             source=("pv1_power", "pv2_power", "pv3_power", "pv4_power")),
    Register(27, "pv1_voltage", "PV1 Voltage", "U16", 10, "V", domain="pv"),
    Register(28, "pv1_current", "PV1 Current", "I16", 100, "A", domain="pv"),
    Register(29, "pv1_power", "PV1 Power", "U16", 1, "W", domain="pv"),
    Register(30, "pv2_voltage", "PV2 Voltage", "U16", 10, "V", domain="pv"),
    Register(31, "pv2_current", "PV2 Current", "I16", 100, "A", domain="pv"),
    Register(32, "pv2_power", "PV2 Power", "U16", 1, "W", domain="pv"),
    Register(33, "pv3_voltage", "PV3 Voltage", "U16", 10, "V", domain="pv"),
    Register(34, "pv3_current", "PV3 Current", "I16", 100, "A", domain="pv"),
    Register(35, "pv3_power", "PV3 Power", "U16", 1, "W", domain="pv"),
    Register(36, "pv4_voltage", "PV4 Voltage", "U16", 10, "V", domain="pv"),
    Register(37, "pv4_current", "PV4 Current", "I16", 100, "A", domain="pv"),
    Register(38, "pv4_power", "PV4 Power", "U16", 1, "W", domain="pv"),

    # --- Battery (inverter DC / legacy) -----------------------------------
    Register(SYNTHETIC_BASE + 1, "bat_total_power", "Battery Total Power", "I16", 1, "W", domain="battery",
             source=("bat1_power_g3",)),
    Register(46, "bat1_voltage", "Battery 1 Voltage", "U16", 10, "V", domain="battery"),
    Register(48, "bat1_current_g3", "Battery 1 Current", "I32", 100, "A", domain="battery"),
    Register(50, "bat1_power_g3", "Battery 1 Power", "I32", 1, "W", domain="battery"),

    # --- Inverter DC bus ---------------------------------------------------
    Register(58, "pos_bus_voltage", "Positive Bus Voltage", "U16", 10, "V", domain="inverter"),
    Register(59, "neg_bus_voltage", "Negative Bus Voltage", "U16", 10, "V", domain="inverter"),
    Register(60, "bus_voltage", "Bus Voltage", "U16", 10, "V", domain="inverter"),

    # --- Grid / AC ---------------------------------------------------------
    Register(62, "grid_voltage_a", "Grid Voltage A", "U16", 10, "V", domain="grid"),
    Register(63, "grid_voltage_b", "Grid Voltage B", "U16", 10, "V", domain="grid"),
    Register(64, "grid_voltage_c", "Grid Voltage C", "U16", 10, "V", domain="grid"),
    Register(66, "grid_frequency", "Grid Frequency", "U16", 100, "Hz", domain="grid"),
    Register(67, "inv_voltage_a", "Inverter Voltage A", "U16", 10, "V", domain="ac"),
    Register(68, "inv_voltage_b", "Inverter Voltage B", "U16", 10, "V", domain="ac"),
    Register(69, "inv_voltage_c", "Inverter Voltage C", "U16", 10, "V", domain="ac"),
    Register(70, "inv_current_a", "Inverter Current A", "I16", 100, "A", domain="ac"),
    Register(71, "inv_current_b", "Inverter Current B", "I16", 100, "A", domain="ac"),
    Register(72, "inv_current_c", "Inverter Current C", "I16", 100, "A", domain="ac"),
    Register(SYNTHETIC_BASE + 2, "inv_active_power", "Inverter Active Power", "I16", 1, "W", domain="ac",
             source=("inv_active_power_a", "inv_active_power_b", "inv_active_power_c")),
    Register(74, "inv_active_power_a", "Inverter Active Power A", "I16", 1, "W", domain="ac"),
    Register(75, "inv_active_power_b", "Inverter Active Power B", "I16", 1, "W", domain="ac"),
    Register(76, "inv_active_power_c", "Inverter Active Power C", "I16", 1, "W", domain="ac"),
    Register(SYNTHETIC_BASE + 3, "inv_reactive_power", "Inverter Reactive Power", "I16", 1, "Var", domain="ac",
             source=("inv_reactive_a", "inv_reactive_b", "inv_reactive_c")),
    Register(78, "inv_reactive_a", "Inverter Reactive A", "I16", 1, "Var", domain="ac"),
    Register(79, "inv_reactive_b", "Inverter Reactive B", "I16", 1, "Var", domain="ac"),
    Register(80, "inv_reactive_c", "Inverter Reactive C", "I16", 1, "Var", domain="ac"),

    # --- Backup / EPS ------------------------------------------------------
    Register(81, "backup_voltage_a", "EPS Voltage A", "U16", 10, "V", domain="backup"),
    Register(82, "backup_voltage_b", "EPS Voltage B", "U16", 10, "V", domain="backup"),
    Register(83, "backup_voltage_c", "EPS Voltage C", "U16", 10, "V", domain="backup"),
    Register(84, "backup_current_a", "EPS Current A", "I16", 100, "A", domain="backup"),
    Register(85, "backup_current_b", "EPS Current B", "I16", 100, "A", domain="backup"),
    Register(86, "backup_current_c", "EPS Current C", "I16", 100, "A", domain="backup"),
    Register(SYNTHETIC_BASE + 4, "backup_apparent_power", "EPS Apparent Power", "I16", 1, "VA", domain="backup",
             source=("backup_apparent_a", "backup_apparent_b", "backup_apparent_c")),
    Register(88, "backup_apparent_a", "EPS Apparent A", "I16", 1, "VA", domain="backup"),
    Register(89, "backup_apparent_b", "EPS Apparent B", "I16", 1, "VA", domain="backup"),
    Register(90, "backup_apparent_c", "EPS Apparent C", "I16", 1, "VA", domain="backup"),
    Register(SYNTHETIC_BASE + 5, "backup_active_power", "EPS Active Power", "I16", 1, "W", domain="backup",
             source=("backup_active_a", "backup_active_b", "backup_active_c")),
    Register(92, "backup_active_a", "EPS Active A", "I16", 1, "W", domain="backup"),
    Register(93, "backup_active_b", "EPS Active B", "I16", 1, "W", domain="backup"),
    Register(94, "backup_active_c", "EPS Active C", "I16", 1, "W", domain="backup"),

    # --- Generator ---------------------------------------------------------
    Register(103, "gen_voltage_a", "Generator Voltage A", "U16", 10, "V", domain="generator"),
    Register(104, "gen_voltage_b", "Generator Voltage B", "U16", 10, "V", domain="generator"),
    Register(105, "gen_voltage_c", "Generator Voltage C", "U16", 10, "V", domain="generator"),
    Register(106, "gen_current_a", "Generator Current A", "I16", 100, "A", domain="generator"),
    Register(107, "gen_current_b", "Generator Current B", "I16", 100, "A", domain="generator"),
    Register(108, "gen_current_c", "Generator Current C", "I16", 100, "A", domain="generator"),
    Register(109, "gen_active_a", "Generator Active A", "I16", 1, "W", domain="generator"),
    Register(110, "gen_active_b", "Generator Active B", "I16", 1, "W", domain="generator"),
    Register(111, "gen_active_c", "Generator Active C", "I16", 1, "W", domain="generator"),

    # --- Thermals / aux / fans / diagnostics -------------------------------
    Register(241, "pe_voltage", "PE Voltage", "I16", 10, "V", domain="inverter"),
    Register(242, "iso_resistor", "Isolation Resistor", "U16", 1, "kOhm", domain="inverter"),
    Register(243, "residual_current", "Residual Current", "I16", 1, "mA", domain="inverter"),
    Register(SYNTHETIC_BASE + 6, "load_power", "Load Power (sum of phases)", "I32", 1, "W", domain="energy",
             source=("load_power_a", "load_power_b", "load_power_c")),
    Register(113, "inv_ths_temp", "Inverter Thermistor Temp", "I16", 1, None, domain="inverter"),
    Register(114, "bat_ths_temp", "Battery Thermistor Temp", "I16", 1, None, domain="inverter"),
    Register(115, "cav_temp", "Cavity Temp", "I16", 1, None, domain="inverter"),
    Register(116, "12v_aux", "12V Aux", "U16", 100, "V", domain="inverter"),
    Register(118, "5v_aux", "5V Aux", "U16", 100, "V", domain="inverter"),
    Register(119, "1_5v_aux", "1.5V Aux", "U16", 100, "V", domain="inverter"),
    Register(120, "relay_aux", "Relay Aux", "U16", 100, "V", domain="inverter"),
    Register(121, "fan_1_speed", "Fan 1 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(122, "fan_2_speed", "Fan 2 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(123, "fan_3_speed", "Fan 3 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(125, "dc_inject_a", "DC Inject A", "I16", 1, "mA", domain="inverter"),
    Register(126, "dc_inject_b", "DC Inject B", "I16", 1, "mA", domain="inverter"),
    Register(127, "dc_inject_c", "DC Inject C", "I16", 1, "mA", domain="inverter"),
    Register(201, "safetydsp_fm_ver", "Safety DSP Firmware Ver", "U16", 1, None, domain="inverter"),
    Register(214, "bus_balance_current", "Bus Balance Current", "I16", 100, "A", domain="inverter"),


    # --- External grid meter block 1800-1827 ------------------------------
    Register(1800, "grid_meter_link", "Grid Meter Link", "U16", 1, None, domain="grid_meter",
             enum={0: "Offline", 1: "Online", 3: "HMID connected", 4: "HMID error"}),
    Register(1801, "meter_grid_voltage_a", "Meter Grid Voltage L1n", "U16", 10, "V", domain="grid_meter"),
    Register(1802, "meter_grid_voltage_b", "Meter Grid Voltage L2n", "U16", 10, "V", domain="grid_meter"),
    Register(1803, "meter_grid_voltage_c", "Meter Grid Voltage L3n", "U16", 10, "V", domain="grid_meter"),
    Register(1804, "meter_current_a", "Meter Current L1n", "I16", 100, "A", domain="grid_meter"),
    Register(1805, "meter_current_b", "Meter Current L2n", "I16", 100, "A", domain="grid_meter"),
    Register(1806, "meter_current_c", "Meter Current L3n", "I16", 100, "A", domain="grid_meter"),
    Register(1807, "meter_grid_freq", "Meter Grid Frequency", "U16", 100, "Hz", domain="grid_meter"),
    Register(1808, "meter_active_a", "Meter Active Power L1n", "I32", 1, "W", domain="grid_meter"),
    Register(1810, "meter_active_b", "Meter Active Power L2n", "I32", 1, "W", domain="grid_meter"),
    Register(1812, "meter_active_c", "Meter Active Power L3n", "I32", 1, "W", domain="grid_meter"),
    Register(1814, "meter_active_total", "Meter Total Active Power", "I32", 1, "W", domain="grid_meter"),
    Register(1816, "meter_reactive_a", "Meter Reactive Power L1n", "I32", 1, "Var", domain="grid_meter"),
    Register(1818, "meter_reactive_b", "Meter Reactive Power L2n", "I32", 1, "Var", domain="grid_meter"),
    Register(1820, "meter_reactive_c", "Meter Reactive Power L3n", "I32", 1, "Var", domain="grid_meter"),
    Register(1822, "meter_reactive_total", "Meter Total Reactive Power", "I32", 1, "Var", domain="grid_meter"),
    Register(1824, "meter_power_factor", "Meter Power Factor", "I16", 100, None, domain="grid_meter"),
    Register(1825, "meter_pf_a", "Meter Power Factor L1n", "I16", 100, None, domain="grid_meter"),
    Register(1826, "meter_pf_b", "Meter Power Factor L2n", "I16", 100, None, domain="grid_meter"),
    Register(1827, "meter_pf_c", "Meter Power Factor L3n", "I16", 100, None, domain="grid_meter"),

    # --- External PV meter block 1850-1877 ---------------------------------
    Register(1850, "pv_meter_link", "PV Meter Link", "U16", 1, None, domain="grid_meter",
             enum={0: "Offline", 1: "Online"}),
    Register(1851, "pv_meter_voltage_a", "PV Meter Voltage L1n", "U16", 10, "V", domain="grid_meter"),
    Register(1852, "pv_meter_voltage_b", "PV Meter Voltage L2n", "U16", 10, "V", domain="grid_meter"),
    Register(1853, "pv_meter_voltage_c", "PV Meter Voltage L3n", "U16", 10, "V", domain="grid_meter"),
    Register(1854, "pv_meter_current_a", "PV Meter Current L1n", "I16", 100, "A", domain="grid_meter"),
    Register(1855, "pv_meter_current_b", "PV Meter Current L2n", "I16", 100, "A", domain="grid_meter"),
    Register(1856, "pv_meter_current_c", "PV Meter Current L3n", "I16", 100, "A", domain="grid_meter"),
    Register(1857, "pv_meter_freq", "PV Meter Frequency", "U16", 100, "Hz", domain="grid_meter"),
    Register(1858, "pv_meter_active_a", "PV Meter Active Power L1n", "I32", 1, "W", domain="grid_meter"),
    Register(1860, "pv_meter_active_b", "PV Meter Active Power L2n", "I32", 1, "W", domain="grid_meter"),
    Register(1862, "pv_meter_active_c", "PV Meter Active Power L3n", "I32", 1, "W", domain="grid_meter"),
    Register(1864, "pv_meter_active_total", "PV Meter Total Active Power", "I32", 1, "W", domain="grid_meter"),
    Register(1866, "pv_meter_reactive_a", "PV Meter Reactive Power L1n", "I32", 1, "Var", domain="grid_meter"),
    Register(1868, "pv_meter_reactive_b", "PV Meter Reactive Power L2n", "I32", 1, "Var", domain="grid_meter"),
    Register(1870, "pv_meter_reactive_c", "PV Meter Reactive Power L3n", "I32", 1, "Var", domain="grid_meter"),
    Register(1872, "pv_meter_reactive_total", "PV Meter Total Reactive Power", "I32", 1, "Var", domain="grid_meter"),
    Register(1874, "pv_meter_power_factor", "PV Meter Power Factor", "I16", 100, None, domain="grid_meter"),
    Register(1875, "pv_meter_pf_a", "PV Meter Power Factor L1n", "I16", 100, None, domain="grid_meter"),
    Register(1876, "pv_meter_pf_b", "PV Meter Power Factor L2n", "I16", 100, None, domain="grid_meter"),
    Register(1877, "pv_meter_pf_c", "PV Meter Power Factor L3n", "I16", 100, None, domain="grid_meter"),

    # --- Battery (BMS block 1900-1923) ------------------------------------
    Register(1900, "bat_type", "Battery Type (BMS)", "U16", 1, None, domain="battery",
             enum={0: "None", 1: "Lithium", 2: "LFP", 3: "Simulated"}),
    Register(1901, "bms_link_status", "BMS Link Status", "U16", 1, None, domain="battery",
             enum={0: "Offline", 1: "Online"}),
    Register(1904, "bat_work_status", "Battery Work Status (BMS)", "U16", 1, None, domain="battery",
             enum={0: "Standby", 1: "Charging", 2: "Discharging"}),
    Register(1905, "bms_fault_code", "BMS Fault Code", "H32", 1, None, domain="battery"),
    Register(1907, "battery_capacity", "Battery Capacity", "H32", 10, "kWh", domain="battery"),
    Register(1909, "battery_soc", "Battery SoC", "U16", 1, "%", domain="battery"),
    Register(1910, "battery_soh", "Battery SOH", "U16", 1, "%", domain="battery"),
    Register(1911, "batt_voltage_bms", "Battery Voltage (BMS)", "U16", 10, "V", domain="battery"),
    Register(1912, "batt_current_bms", "Battery Current (BMS)", "I32", 10, "A", domain="battery"),
    Register(1914, "batt_power_bms", "Battery Power (BMS)", "I32", 1, "W", domain="battery"),
    Register(1916, "max_charge_current", "Max Charge Current", "U16", 10, "A", domain="battery"),
    Register(1917, "max_discharge_current", "Max Discharge Current", "U16", 10, "A", domain="battery"),
    Register(1918, "charge_cutoff_v", "Charge Cutoff Voltage", "U16", 10, "V", domain="battery"),
    Register(1919, "discharge_cutoff_v", "Discharge Cutoff Voltage", "U16", 10, "V", domain="battery"),
    Register(1922, "batt_max_cell_temp", "Battery Max Cell Temp", "U16", 10, None, domain="battery"),
    Register(1923, "batt_min_cell_temp", "Battery Min Cell Temp", "U16", 10, None, domain="battery"),

    # --- Energy: lifetime --------------------------------------------------
    Register(2000, "pv_total_energy", "PV Total Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2002, "pv1_energy_total", "PV1 Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2004, "pv2_energy_total", "PV2 Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2006, "pv3_energy_total", "PV3 Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2008, "pv4_energy_total", "PV4 Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2014, "external_pv_energy", "External PV Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2016, "external_pv_energy_a", "External PV Energy L1n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2018, "external_pv_energy_b", "External PV Energy L2n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2020, "external_pv_energy_c", "External PV Energy L3n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2022, "pv_bat_energy", "PV->Battery Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2024, "pv_load_energy", "PV->Load Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2026, "pv_grid_energy", "PV->Grid Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2028, "bat_charge_energy", "Battery Charge Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2030, "bat_discharge_energy", "Battery Discharge Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2040, "grid_buy_energy", "Grid Buy Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2042, "grid_buy_energy_a", "Grid Buy Energy L1n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2044, "grid_buy_energy_b", "Grid Buy Energy L2n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2046, "grid_buy_energy_c", "Grid Buy Energy L3n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2048, "grid_sell_energy", "Grid Sell Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2050, "grid_sell_energy_a", "Grid Sell Energy L1n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2052, "grid_sell_energy_b", "Grid Sell Energy L2n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2054, "grid_sell_energy_c", "Grid Sell Energy L3n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2056, "load_energy_use", "Load Energy Use Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2058, "load_energy_a", "Load Energy Use L1n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2060, "load_energy_b", "Load Energy Use L2n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2062, "load_energy_c", "Load Energy Use L3n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2064, "energy_from_pv", "Energy From PV Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2066, "energy_from_bat", "Energy From Battery Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2068, "energy_from_grid", "Energy From Grid Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2070, "gen_energy_total", "Generator Energy Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2072, "gen_energy_a", "Generator Energy L1n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2074, "gen_energy_b", "Generator Energy L2n Lifetime", "U32", 10, "kWh", domain="energy"),
    Register(2076, "gen_energy_c", "Generator Energy L3n Lifetime", "U32", 10, "kWh", domain="energy"),

    # --- Energy: today ------------------------------------------------------
    Register(2100, "pv_today_energy", "PV Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2101, "pv1_today_energy", "PV1 Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2102, "pv2_today_energy", "PV2 Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2103, "pv3_today_energy", "PV3 Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2104, "pv4_today_energy", "PV4 Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2107, "ext_pv_today", "External PV Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2108, "external_pv_today_a", "External PV Energy L1n Today", "U16", 10, "kWh", domain="energy"),
    Register(2109, "external_pv_today_b", "External PV Energy L2n Today", "U16", 10, "kWh", domain="energy"),
    Register(2110, "external_pv_today_c", "External PV Energy L3n Today", "U16", 10, "kWh", domain="energy"),
    Register(2111, "pv_bat_today", "PV->Battery Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2112, "pv_load_today", "PV->Load Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2113, "pv_grid_today", "PV->Grid Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2114, "bat_charge_today", "Battery Charge Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2115, "bat_discharge_today", "Battery Discharge Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2120, "grid_buy_today", "Grid Buy Today", "U16", 10, "kWh", domain="energy"),
    Register(2121, "grid_buy_today_a", "Grid Buy L1n Today", "U16", 10, "kWh", domain="energy"),
    Register(2122, "grid_buy_today_b", "Grid Buy L2n Today", "U16", 10, "kWh", domain="energy"),
    Register(2123, "grid_buy_today_c", "Grid Buy L3n Today", "U16", 10, "kWh", domain="energy"),
    Register(2124, "grid_sell_today", "Grid Sell Today", "U16", 10, "kWh", domain="energy"),
    Register(2125, "grid_sell_today_a", "Grid Sell L1n Today", "U16", 10, "kWh", domain="energy"),
    Register(2126, "grid_sell_today_b", "Grid Sell L2n Today", "U16", 10, "kWh", domain="energy"),
    Register(2127, "grid_sell_today_c", "Grid Sell L3n Today", "U16", 10, "kWh", domain="energy"),
    Register(2128, "load_energy_today", "Load Energy Use Today", "U16", 10, "kWh", domain="energy"),
    Register(2129, "load_energy_today_a", "Load Energy Use L1n Today", "U16", 10, "kWh", domain="energy"),
    Register(2130, "load_energy_today_b", "Load Energy Use L2n Today", "U16", 10, "kWh", domain="energy"),
    Register(2131, "load_energy_today_c", "Load Energy Use L3n Today", "U16", 10, "kWh", domain="energy"),
    Register(2132, "energy_from_pv_today", "Energy From PV Today", "U16", 10, "kWh", domain="energy"),
    Register(2133, "energy_from_bat_today", "Energy From Battery Today", "U16", 10, "kWh", domain="energy"),
    Register(2134, "energy_from_grid_today", "Energy From Grid Today", "U16", 10, "kWh", domain="energy"),
    Register(2135, "gen_energy_today", "Generator Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2136, "gen_energy_today_a", "Generator Energy L1n Today", "U16", 10, "kWh", domain="energy"),
    Register(2137, "gen_energy_today_b", "Generator Energy L2n Today", "U16", 10, "kWh", domain="energy"),
    Register(2138, "gen_energy_today_c", "Generator Energy L3n Today", "U16", 10, "kWh", domain="energy"),

    # --- Power / energy-flow block 2150-2180 -------------------------------
    Register(2150, "pv_total_power_eb", "PV Total Power (Energy Block)", "U16", 1, "W", domain="energy"),
    Register(2152, "pv1_power_eb", "PV1 Power (Energy Block)", "U16", 1, "W", domain="energy"),
    Register(2153, "pv2_power_eb", "PV2 Power (Energy Block)", "U16", 1, "W", domain="energy"),
    Register(2154, "pv3_power_eb", "PV3 Power (Energy Block)", "U16", 1, "W", domain="energy"),
    Register(2155, "pv4_power_eb", "PV4 Power (Energy Block)", "U16", 1, "W", domain="energy"),
    Register(2158, "external_pv_power_total", "External PV Total Power", "U16", 1, "W", domain="energy"),
    Register(2159, "external_pv_power_a", "External PV Power L1n", "U16", 1, "W", domain="energy"),
    Register(2160, "external_pv_power_b", "External PV Power L2n", "U16", 1, "W", domain="energy"),
    Register(2161, "external_pv_power_c", "External PV Power L3n", "U16", 1, "W", domain="energy"),
    Register(2162, "battery_power_eb", "Battery Total Power (Energy Block)", "I16", 1, "W", domain="energy"),
    Register(2165, "grid_active_power_total", "Grid Active Power", "I16", 1, "W", domain="energy"),
    Register(2166, "grid_active_a", "Grid Active Power L1", "I16", 1, "W", domain="energy"),
    Register(2167, "grid_active_b", "Grid Active Power L2", "I16", 1, "W", domain="energy"),
    Register(2168, "grid_active_c", "Grid Active Power L3", "I16", 1, "W", domain="energy"),
    Register(2169, "load_power_total", "Load Power Total", "I16", 1, "W", domain="energy"),
    Register(2170, "load_power_a", "Load Power L1n", "I16", 1, "W", domain="energy"),
    Register(2171, "load_power_b", "Load Power L2n", "I16", 1, "W", domain="energy"),
    Register(2172, "load_power_c", "Load Power L3n", "I16", 1, "W", domain="energy"),
    Register(2173, "gen_power_total", "Generator Total Power", "I16", 1, "W", domain="energy"),
    Register(2174, "gen_power_a", "Generator Power L1n", "I16", 1, "W", domain="energy"),
    Register(2175, "gen_power_b", "Generator Power L2n", "I16", 1, "W", domain="energy"),
    Register(2176, "gen_power_c", "Generator Power L3n", "I16", 1, "W", domain="energy"),
    Register(2177, "pv_to_battery_power", "PV to Battery Power", "U16", 1, "W", domain="energy"),
    Register(2178, "pv_to_load_power", "PV to Load Power", "U16", 1, "W", domain="energy"),
    Register(2179, "pv_to_grid_power", "PV to Grid Power", "U16", 1, "W", domain="energy"),
    Register(2180, "load_from_pv_power", "Load From PV Power", "U16", 1, "W", domain="energy"),

    # --- Overview / status block 30000-30029 -------------------------------
    Register(30000, "system_workstatus", "Overview System Work Status", "U16", 1, None, domain="status",
             enum={0: "Power-up", 1: "Standby", 2: "Grid test", 3: "Grid on",
                   4: "Fault", 5: "Islanded", 6: "Bypass"}),
    Register(30001, "pv_total_power_ov", "Overview PV Total Power", "H32", 1, "W", domain="status"),
    Register(30003, "internal_pv_power_ov", "Overview Internal PV Total Power", "H32", 1, "W", domain="status"),
    Register(30005, "external_pv_power_ov", "Overview External PV Total Power", "H32", 1, "W", domain="status"),
    Register(30007, "inv_active_power_ov", "Overview Inverter Active Power", "I32", 1, "W", domain="status"),
    Register(30009, "battery_power_ov", "Overview Battery Power", "I32", 1, "W", domain="status"),
    Register(30011, "grid_active_power_ov", "Overview Grid Total Active Power", "I32", 1, "W", domain="status"),
    Register(30013, "generator_power_ov", "Overview Generator Active Power", "I32", 1, "W", domain="status"),
    Register(30015, "load_active_power_ov", "Overview Load Active Power", "I32", 1, "W", domain="status"),
    Register(30017, "smart_load_power_ov", "Overview Smart Load Active Power", "I32R", 1, "W", domain="status"),
    Register(30019, "battery_work_status", "Overview Battery Work Status", "U16", 1, None, domain="status",
             enum={0: "Standby", 1: "Charging", 2: "Discharging"}),
    Register(30020, "battery_soc_ov", "Overview Battery SOC", "U16", 1, "%", domain="status"),
    Register(30021, "battery_faults", "Battery Faults", "H32", 1, None, domain="status", bitmap={
        0: "Low battery voltage", 1: "High battery voltage",
        2: "Low pack voltage on discharge", 3: "High pack voltage on charge",
        4: "Low charge temp", 5: "High charge temp",
        6: "Low discharge temp", 7: "High discharge temp",
        8: "High HV input voltage"}),
    Register(30023, "dsp_pwr_faults", "DSP Power Faults", "H32", 1, None, domain="status", bitmap={
        0: "Shutdown", 1: "Hardware protection", 2: "Comparator error",
        3: "SPI comm error", 4: "ARM comm error", 5: "Invalid measurement offset",
        6: "CMPSS offset error", 7: "EEPROM error", 8: "PV error",
        9: "Battery error", 10: "Invalid auxiliary power", 11: "Grid relay protection",
        12: "Invalid DC bus", 13: "Fan error", 14: "Device type mismatch",
        15: "Version mismatch", 16: "Incorrect wiring", 17: "PV above bus voltage",
        18: "Power driver error", 19: "Invalid temperature", 20: "EPS relay protection",
        21: "Low battery energy", 22: "Invalid EPS voltage", 23: "EPS overload",
        24: "Generator error", 25: "Generator overload", 26: "Meter wiring error",
        27: "CAN comm timeout", 28: "Pre-sync failure", 29: "PLL sync lost",
        30: "Invalid grid voltage"}),
    Register(30025, "dsp_safety_faults", "DSP Safety Faults", "H32", 1, None, domain="status", bitmap={
        0: "Grid voltage too high", 1: "Grid voltage too low", 2: "10-min voltage exceeded",
        3: "Grid freq too high", 4: "Grid freq too low", 5: "Freq change too fast",
        6: "Reconnect failed", 7: "Grid loss", 8: "N not connected",
        9: "Phase-PE short", 10: "N-PE short", 11: "Device type mismatch",
        12: "Version mismatch", 13: "AFCI self-test error", 14: "AFCI arc error",
        15: "Isolation error", 16: "RCD self-test error", 17: "RCD error",
        18: "Grid relay protection", 19: "Invalid auxiliary power", 20: "SPI comm error",
        21: "ARM comm error", 22: "Invalid measurement offset", 23: "Flash comm error",
        24: "Off-grid DC component out of range", 25: "Grid DC current out of range",
        26: "Interrupt overflow", 27: "MCU error", 28: "Ambient temp too low",
        29: "Overheating", 30: "Comparator error", 31: "Fan error"}),
    Register(30027, "arm_comm_faults", "ARM Communication Faults", "U16", 1, None, domain="status", bitmap={
        5: "DSP_PWR comm lost", 6: "DSP_SAF comm lost"}),
    Register(30028, "arm_periph_faults", "ARM Peripheral Faults", "U16", 1, None, domain="status", bitmap={
        1: "PV meter comm lost", 2: "Grid meter comm lost", 3: "BMS CAN comm lost",
        4: "DTU version too low", 5: "DTS comm lost", 6: "Invalid grid meter type",
        7: "Invalid PV meter type", 8: "Slave battery wiring error",
        9: "DTU1 RS485 lost", 10: "DTU2 RS485 lost", 11: "DTU3 RS485 lost",
        12: "DTU4 RS485 lost", 13: "DTU5 RS485 lost", 14: "EV1 charger comm lost",
        15: "EV2 charger comm lost"}),
    Register(30029, "arm_system_faults", "ARM System Faults", "U16", 1, None, domain="status", bitmap={
        0: "EV1 charger error", 1: "EV2 charger error",
        2: "Persistently negative load power", 3: "Invalid battery capacity"}),

    # --- Settings (holding registers) --------------------------------------
    Register(258, "gcf_enable", "Generation Control Function", "U16", 1, None, domain="settings", kind="holding"),
    Register(259, "gcf_export_limit", "GCF Maximum Export Ratio", "I16", 10, "%", domain="settings", kind="holding"),
    Register(303, "gen_port_mode", "GEN Port Mode", "U16", 1, None, domain="settings", kind="holding"),
    Register(306, "battery_max_charge_power", "Battery Max Charge Power", "U16", 10, "%", domain="settings", kind="holding"),
    Register(307, "battery_max_discharge_power", "Battery Max Discharge Power", "U16", 10, "%", domain="settings", kind="holding"),
    Register(308, "max_soc", "Maximum SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(309, "min_soc", "Minimum SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(310, "low_soc_grid_charge_power", "Low SOC Grid Charge Power", "U16", 1, "W", domain="settings", kind="holding"),
    Register(311, "soc_start_charge_from_grid", "SOC Start Charge From Grid", "U16", 1, "%", domain="settings", kind="holding"),
    Register(323, "eps_mode", "EPS Mode", "U16", 1, None, domain="settings", kind="holding"),
    Register(324, "pv_island_mode", "PV Island Mode", "U16", 1, None, domain="settings", kind="holding"),
    Register(3001, "system_operation", "System Operation", "U16", 1, None, domain="settings", kind="holding"),
    Register(3016, "parallel_networking_cmd", "Parallel Networking Command", "U16", 1, None, domain="settings", kind="holding"),
    Register(4100, "battery_type_setting", "Battery Type Setting", "U16", 1, None, domain="settings", kind="holding"),
    Register(4101, "bms_type_setting", "BMS Type Setting", "U16", 1, None, domain="settings", kind="holding"),
    Register(4102, "battery_capacity_setting", "Battery Capacity Setting", "U16", 10, "kWh", domain="settings", kind="holding"),
    Register(4300, "ems_mode", "EMS Mode", "U16", 1, None, domain="settings", kind="holding",
             enum={0: "Self-use", 3: "Off-Grid", 4: "Grid charge", 5: "Grid discharge"}),
    Register(4301, "ems_self_use_soc", "EMS Self-Use SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(4302, "ems_backup_soc", "EMS Backup SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(4303, "ems_force_charge_soc", "EMS Force Charge SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(4304, "ems_max_charge_power", "EMS Maximum Charge Power", "U16", 10, "%", domain="settings", kind="holding"),
    Register(4305, "ems_force_discharge_soc", "EMS Force Discharge SOC", "U16", 1, "%", domain="settings", kind="holding"),
    Register(4306, "ems_max_discharge_power", "EMS Maximum Discharge Power", "U16", 10, "%", domain="settings", kind="holding"),
    Register(6048, "machines_type", "Topology Machinery Type", "U16", 1, None, domain="settings", kind="holding",
             enum={0: "Single", 1: "Master", 2: "Slave"}),
    Register(6049, "machine_count", "Number of Machines", "U16", 1, None, domain="settings", kind="holding"),

)

WSIZE: dict[str, int] = {"U16": 1, "I16": 1, "U32": 2, "I32": 2, "H32": 2, "F32": 2, "I32R": 2}


REGISTERS_BY_KEY: dict[str, Register] = {r.key: r for r in REGISTERS}
REGISTERS_BY_ADDR: dict[int, Register] = {r.addr: r for r in REGISTERS}
