"""Hoymiles G3 input-register catalog (transcribed verbatim from reference manifest.py::R)."""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Register:
    addr: int
    key: str
    label: str
    dtype: str
    scale: float = 1.0
    unit: str | None = None
    domain: str = ""
    doc: str = ""
    source: tuple[str, ...] = ()


REGISTERS: tuple[Register, ...] = (
    Register(0, "workstatus", "Work Status", "U16", 1, None, domain="inverter"),
    Register(1, "powerdsp_fm_ver", "Power DSP Firmware Version", "U16", 1, None, domain="inverter"),
    Register(19, "sw_fault", "Software Fault", "H32", 1, None, domain="inverter"),
    Register(21, "hw_fault", "Hardware Fault", "H32", 1, None, domain="inverter"),
    Register(26, "pv_total_power", "PV Total Power", "U16", 1, "W", domain="pv", source=("pv1_power", "pv2_power", "pv3_power", "pv4_power")),
    Register(27, "pv1_voltage", "PV1 Voltage", "U16", 10, "V", domain="pv"),
    Register(28, "pv1_current", "PV1 Current", "I16", 100, "A", domain="pv"),
    Register(29, "pv1_power", "PV1 Power", "U16", 1, "W", domain="pv"),
    Register(30, "pv2_voltage", "PV2 Voltage", "U16", 10, "V", domain="pv"),
    Register(31, "pv2_current", "PV2 Current", "I16", 100, "A", domain="pv"),
    Register(32, "pv2_power", "PV2 Power", "U16", 1, "W", domain="pv"),
    Register(33, "pv3_voltage", "PV3 Voltage", "U16", 10, "V", domain="pv"),
    Register(34, "pv3_current", "PV3 Current", "I16", 100, "A", domain="pv"),
    Register(35, "pv3_power", "PV3 Power", "U16", 1, "W", domain="pv"),
    Register(36, "pv4_voltage", "PV4 Voltage", "U16", 10, "V", domain="pv"),
    Register(37, "pv4_current", "PV4 Current", "I16", 100, "A", domain="pv"),
    Register(38, "pv4_power", "PV4 Power", "U16", 1, "W", domain="pv"),
    Register(45, "bat_total_power", "Battery Total Power", "I16", 1, "W", domain="battery", source=("bat1_power_g3",)),
    Register(46, "bat1_voltage", "Battery 1 Voltage", "U16", 10, "V", domain="battery"),
    Register(48, "bat1_current_g3", "Battery 1 Current", "I32", 100, "A", domain="battery"),
    Register(50, "bat1_power_g3", "Battery 1 Power", "I32", 1, "W", domain="battery"),
    Register(58, "pos_bus_voltage", "Positive Bus Voltage", "U16", 10, "V", domain="inverter"),
    Register(59, "neg_bus_voltage", "Negative Bus Voltage", "U16", 10, "V", domain="inverter"),
    Register(60, "bus_voltage", "Bus Voltage", "U16", 10, "V", domain="inverter"),
    Register(62, "grid_voltage_a", "Grid Voltage A", "U16", 10, "V", domain="grid"),
    Register(63, "grid_voltage_b", "Grid Voltage B", "U16", 10, "V", domain="grid"),
    Register(64, "grid_voltage_c", "Grid Voltage C", "U16", 10, "V", domain="grid"),
    Register(66, "grid_frequency", "Grid Frequency", "U16", 100, "Hz", domain="grid"),
    Register(67, "inv_voltage_a", "Inverter Voltage A", "U16", 10, "V", domain="ac"),
    Register(68, "inv_voltage_b", "Inverter Voltage B", "U16", 10, "V", domain="ac"),
    Register(69, "inv_voltage_c", "Inverter Voltage C", "U16", 10, "V", domain="ac"),
    Register(70, "inv_current_a", "Inverter Current A", "I16", 100, "A", domain="ac"),
    Register(71, "inv_current_b", "Inverter Current B", "I16", 100, "A", domain="ac"),
    Register(72, "inv_current_c", "Inverter Current C", "I16", 100, "A", domain="ac"),
    Register(73, "inv_active_power", "Inverter Active Power", "I16", 1, "W", domain="ac", source=("inv_active_power_a", "inv_active_power_b", "inv_active_power_c")),
    Register(74, "inv_active_power_a", "Inverter Active Power A", "I16", 1, "W", domain="ac"),
    Register(75, "inv_active_power_b", "Inverter Active Power B", "I16", 1, "W", domain="ac"),
    Register(76, "inv_active_power_c", "Inverter Active Power C", "I16", 1, "W", domain="ac"),
    Register(77, "inv_reactive_power", "Inverter Reactive Power", "I16", 1, "Var", domain="ac", source=("inv_reactive_a", "inv_reactive_b", "inv_reactive_c")),
    Register(78, "inv_reactive_a", "Inverter Reactive A", "I16", 1, "Var", domain="ac"),
    Register(79, "inv_reactive_b", "Inverter Reactive B", "I16", 1, "Var", domain="ac"),
    Register(80, "inv_reactive_c", "Inverter Reactive C", "I16", 1, "Var", domain="ac"),
    Register(81, "backup_voltage_a", "EPS Voltage A", "U16", 10, "V", domain="backup"),
    Register(82, "backup_voltage_b", "EPS Voltage B", "U16", 10, "V", domain="backup"),
    Register(83, "backup_voltage_c", "EPS Voltage C", "U16", 10, "V", domain="backup"),
    Register(84, "backup_current_a", "EPS Current A", "I16", 100, "A", domain="backup"),
    Register(85, "backup_current_b", "EPS Current B", "I16", 100, "A", domain="backup"),
    Register(86, "backup_current_c", "EPS Current C", "I16", 100, "A", domain="backup"),
    Register(87, "backup_apparent_power", "EPS Apparent Power", "I16", 1, "VA", domain="backup", source=("backup_apparent_a", "backup_apparent_b", "backup_apparent_c")),
    Register(88, "backup_apparent_a", "EPS Apparent A", "I16", 1, "VA", domain="backup"),
    Register(89, "backup_apparent_b", "EPS Apparent B", "I16", 1, "VA", domain="backup"),
    Register(90, "backup_apparent_c", "EPS Apparent C", "I16", 1, "VA", domain="backup"),
    Register(91, "backup_active_power", "EPS Active Power", "I16", 1, "W", domain="backup", source=("backup_active_a", "backup_active_b", "backup_active_c")),
    Register(92, "backup_active_a", "EPS Active A", "I16", 1, "W", domain="backup"),
    Register(93, "backup_active_b", "EPS Active B", "I16", 1, "W", domain="backup"),
    Register(94, "backup_active_c", "EPS Active C", "I16", 1, "W", domain="backup"),
    Register(103, "gen_voltage_a", "Generator Voltage A", "U16", 10, "V", domain="generator"),
    Register(104, "gen_voltage_b", "Generator Voltage B", "U16", 10, "V", domain="generator"),
    Register(105, "gen_voltage_c", "Generator Voltage C", "U16", 10, "V", domain="generator"),
    Register(106, "gen_current_a", "Generator Current A", "I16", 100, "A", domain="generator"),
    Register(107, "gen_current_b", "Generator Current B", "I16", 100, "A", domain="generator"),
    Register(108, "gen_current_c", "Generator Current C", "I16", 100, "A", domain="generator"),
    Register(109, "gen_active_a", "Generator Active A", "I16", 1, "W", domain="generator"),
    Register(110, "gen_active_b", "Generator Active B", "I16", 1, "W", domain="generator"),
    Register(111, "gen_active_c", "Generator Active C", "I16", 1, "W", domain="generator"),
    Register(112, "pv_ths_temp", "PV Thermistor Temp", "I16", 1, None, domain="inverter"),
    Register(113, "inv_ths_temp", "Inverter Thermistor Temp", "I16", 1, None, domain="inverter"),
    Register(114, "bat_ths_temp", "Battery Thermistor Temp", "I16", 1, None, domain="inverter"),
    Register(115, "cav_temp", "Cavity Temp", "I16", 1, None, domain="inverter"),
    Register(116, "12v_aux", "12V Aux", "U16", 100, "V", domain="inverter"),
    Register(118, "5v_aux", "5V Aux", "U16", 100, "V", domain="inverter"),
    Register(119, "1_5v_aux", "1.5V Aux", "U16", 100, "V", domain="inverter"),
    Register(120, "relay_aux", "Relay Aux", "U16", 100, "V", domain="inverter"),
    Register(121, "fan_1_speed", "Fan 1 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(122, "fan_2_speed", "Fan 2 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(123, "fan_3_speed", "Fan 3 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(125, "dc_inject_a", "DC Inject A", "I16", 1, "mA", domain="inverter"),
    Register(126, "dc_inject_b", "DC Inject B", "I16", 1, "mA", domain="inverter"),
    Register(127, "dc_inject_c", "DC Inject C", "I16", 1, "mA", domain="inverter"),
    Register(1030, "batt_max_cell_temp", "Battery Max Cell Temp", "U16", 10, None, domain="battery"),
    Register(1031, "batt_min_cell_temp", "Battery Min Cell Temp", "U16", 10, None, domain="battery"),
    Register(1032, "batt_voltage_bms", "Battery Voltage (BMS)", "U16", 10, "V", domain="battery"),
    Register(1033, "batt_current_bms", "Battery Current (BMS)", "I16", 10, "A", domain="battery"),
    Register(1050, "meter_current_a", "Meter Current A", "I16", 100, "A", domain="grid_meter"),
    Register(1051, "meter_current_b", "Meter Current B", "I16", 100, "A", domain="grid_meter"),
    Register(1052, "meter_current_c", "Meter Current C", "I16", 100, "A", domain="grid_meter"),
    Register(153, "ext_fan_1_speed", "External Fan 1 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(154, "ext_fan_2_speed", "External Fan 2 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(155, "ext_fan_3_speed", "External Fan 3 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(156, "ext_fan_4_speed", "External Fan 4 Speed", "U16", 1, "r/m", domain="inverter"),
    Register(201, "safetydsp_fm_ver", "Safety DSP Firmware Ver", "U16", 1, None, domain="inverter"),
    Register(214, "bus_balance_current", "Bus Balance Current", "I16", 100, "A", domain="inverter"),
    Register(242, "iso_resistor", "Isolation Resistor", "U16", 1, "kOhm", domain="inverter"),
    Register(243, "residual_current", "Residual Current", "I16", 1, "mA", domain="inverter"),
    Register(1021, "bat_type", "Battery Type", "U16", 1, None, domain="battery"),
    Register(1022, "bms_link_status", "BMS Link Status", "U16", 1, None, domain="battery"),
    Register(1023, "bms_fault_code", "BMS Fault Code", "U16", 1, None, domain="battery"),
    Register(1024, "battery_capacity", "Battery Capacity", "U16", 10, "kWh", domain="battery"),
    Register(1025, "battery_soc", "Battery SoC", "U16", 1, "%", domain="battery"),
    Register(1026, "charge_cutoff_v", "Charge Cutoff Voltage", "U16", 10, "V", domain="battery"),
    Register(1027, "discharge_cutoff_v", "Discharge Cutoff Voltage", "U16", 10, "V", domain="battery"),
    Register(1028, "max_charge_current", "Max Charge Current", "U16", 10, "A", domain="battery"),
    Register(1029, "max_discharge_current", "Max Discharge Current", "U16", 10, "A", domain="battery"),
    Register(1046, "grid_meter_link", "Grid Meter Link", "U16", 1, None, domain="grid_meter"),
    Register(1047, "meter_grid_voltage_a", "Meter Grid Voltage A", "U16", 10, "V", domain="grid_meter"),
    Register(1048, "meter_grid_voltage_b", "Meter Grid Voltage B", "U16", 10, "V", domain="grid_meter"),
    Register(1049, "meter_grid_voltage_c", "Grid Voltage C", "U16", 10, "V", domain="grid_meter"),
    Register(1053, "meter_grid_freq", "Grid Frequency", "U16", 100, "Hz", domain="grid_meter"),
    Register(1060, "drm_status", "DRM status", "U16", 1, None, domain="grid_meter"),
    Register(1061, "pv_meter_link", "PV Meter Link", "U16", 1, None, domain="grid_meter"),
    Register(1078, "grid_active_power_a", "Grid Active Power A", "I32", 1, "W", domain="grid"),
    Register(1080, "grid_active_power_b", "Grid Active Power B", "I32", 1, "W", domain="grid"),
    Register(1082, "grid_active_power_c", "Grid Active Power C", "I32", 1, "W", domain="grid"),
    Register(1084, "grid_reactive_a", "Grid Reactive Power A", "I32", 1, "Var", domain="grid"),
    Register(1086, "grid_reactive_b", "Grid Reactive Power B", "I32", 1, "Var", domain="grid"),
    Register(1088, "grid_reactive_c", "Grid Reactive Power C", "I32", 1, "Var", domain="grid"),
    Register(1090, "pv_inv_active_a", "PV Inverter Active Power A", "I32", 1, "W", domain="pv"),
    Register(1092, "pv_inv_active_b", "PV Inverter Active Power B", "I32", 1, "W", domain="pv"),
    Register(1094, "pv_inv_active_c", "PV Inverter Active Power C", "I32", 1, "W", domain="pv"),
    Register(2000, "pv_total_energy", "PV Total Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2014, "external_pv_energy", "External PV Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2022, "pv_bat_energy", "PV->Battery Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2024, "pv_load_energy", "PV->Load Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2026, "pv_grid_energy", "PV->Grid Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2028, "bat_charge_energy", "Battery Charge Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2030, "bat_discharge_energy", "Battery Discharge Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2040, "grid_buy_energy", "Grid Buy Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2048, "grid_sell_energy", "Grid Sell Energy Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2056, "load_energy_use", "Load Energy Use Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2064, "energy_from_pv", "Energy From PV Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2066, "energy_from_bat", "Energy From Battery Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2068, "energy_from_grid", "Energy From Grid Lifetime", "I32", 10, "kWh", domain="energy"),
    Register(2100, "pv_today_energy", "PV Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2107, "ext_pv_today", "External PV Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2111, "pv_bat_today", "PV->Battery Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2112, "pv_load_today", "PV->Load Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2113, "pv_grid_today", "PV->Grid Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2114, "bat_charge_today", "Battery Charge Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2115, "bat_discharge_today", "Battery Discharge Energy Today", "U16", 10, "kWh", domain="energy"),
    Register(2120, "grid_buy_today", "Grid Buy Today", "U16", 10, "kWh", domain="energy"),
    Register(2124, "grid_sell_today", "Grid Sell Today", "U16", 10, "kWh", domain="energy"),
    Register(2132, "energy_from_pv_today", "Energy From PV Today", "U16", 10, "kWh", domain="energy"),
    Register(2133, "energy_from_bat_today", "Energy From Battery Today", "U16", 10, "kWh", domain="energy"),
    Register(2134, "energy_from_grid_today", "Energy From Grid Today", "U16", 10, "kWh", domain="energy"),
    Register(2135, "gen_energy_today", "Generator Energy Today", "U16", 10, "kWh", domain="energy"),
)

WSIZE: dict[str, int] = {"U16": 1, "I16": 1, "I32": 2, "H32": 2, "F32": 2}

REGISTERS_BY_KEY: dict[str, Register] = {r.key: r for r in REGISTERS}
REGISTERS_BY_ADDR: dict[int, Register] = {r.addr: r for r in REGISTERS}
